# Copyright (c) 2023, WSO2 LLC. (https://www.wso2.com).
#
# WSO2 LLC. licenses this file to you under the Apache License,
# Version 2.0 (the "License"); you may not use this file except
# in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied. See the License for the
# specific language governing permissions and limitations
# under the License.

site_name: ""
site_author: WSO2

# Repository
repo_name: wso2/docs-is
# repo_url: https://github.com/wso2/docs-is
# edit_uri: https://github.com/wso2/docs-is/edit/master/en/docs/

# Copyright
copyright: © 2023 WSO2 LLC.

# Configuration
theme:
  name: material
  font:
    text: Nunito
  toc: false
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.indexes
    - navigation.path
    - navigation.top
    - content.code.copy
    - content.action.edit
    - content.action.view
    - content.tabs.link
    - search.suggest
    - search.share
  language: 'en'
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default 
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
  icon:
    logo: logo
#Breaks build if there's a warning
strict: false

# Extensions
markdown_extensions:
  - markdown.extensions.admonition
  - markdown.extensions.def_list
  - markdown.extensions.footnotes
  - admonition
  - markdown.extensions.toc:
      permalink: true
      toc_depth: 3
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - pymdownx.snippets:
      base_path: docs
  - attr_list

extra_css:
  - assets/libs/fontawesome-free-6.4.2-web/css/all.min.css 
  - assets/css/overrides.css
  # TODO: Need to verify if below css files are still needed. And clean those.
  # - assets/lib/highlightjs/default.min.css
  # - assets/css/theme.css
  # - assets/css/prism.css
  # - assets/lib/json-formatter/json-formatter.css
  # - assets/lib/highlightjs/styles/vs.min.css
  # - assets/css/blue-palette-alt2.css
  # - assets/lib/json-formatter/json-formatter.css
  # - assets/css/config-catalog.css
extra_javascript:
  - assets/js/theme.js
  # TODO: Need to verify if below js files are still needed. And clean those.
  # - assets/lib/json-formatter/json-formatter.umd.js
  # - assets/lib/highlightjs/highlight.min.js
# validation:
#   nav:
#     omitted_files: info
#     not_found: warn
#     absolute_links: info
#   links:
#     not_found: warn
#     absolute_links: info
#     unrecognized_links: info
extra:
  doc_base: &doc_base https://is.docs.wso2.com/en
  material:
    jinja2content: true
  generator: false
  # social:
  #   - icon: fontawesome/brands/github
  #     link: https://github.com/wso2
  integrations:
    - name: Asgardeo Auth React SDK
      icon: assets/img/logo/react-logo.svg
      description: An Asgardeo SDK to integrate Asgardeo into React applications
      documentation_link: get-started/try-your-own-app/javascript/
      download_link: https://github.com/asgardeo/asgardeo-auth-react-sdk/releases/latest/download/asgardeo-react-app.zip
      source_link: https://github.com/asgardeo/asgardeo-auth-react-sdk
    - name: Asgardeo Auth SPA SDK
      icon: assets/img/logo/javascript-logo.svg
      description: An Asgardeo SDK to integrate Asgardeo into single page applications
      documentation_link: get-started/try-your-own-app/javascript/
      download_link: https://github.com/asgardeo/asgardeo-auth-spa-sdk/releases/latest/download/asgardeo-html-js-app.zip
      source_link: https://github.com/asgardeo/asgardeo-auth-spa-sdk
    - name: Angular OAuth2 OIDC
      icon: assets/img/logo/angular-logo.svg
      description: A library for implementing OAuth2 and OIDC in Angular applications
      source_link: https://github.com/manfredsteyer/angular-oauth2-oidc
    - name: Next Auth
      icon: assets/img/logo/nextjs-logo.svg
      description: A library for implementing OAuth2 and OIDC in NextJS applications
      source_link: https://github.com/nextauthjs/next-auth
    - name: Asgardeo Auth Node SDK
      icon: assets/img/logo/expressjs-logo.svg
      description: An Asgardeo SDK to integrate WSO2 IS into JS/TS-based frameworks such as ExpressJS
      source_link: https://github.com/asgardeo/asgardeo-auth-node-sdk
    - name: Asgardeo Tomcat OIDC Agent
      icon: assets/img/logo/java-logo.svg
      description: An Asgardeo Tomcat agent for implementing login/logout for Tomcat web apps
      documentation_link: get-started/try-your-own-app/java-ee-oidc/
      download_link: https://github.com/asgardeo/asgardeo-tomcat-oidc-agent/releases/latest/download/oidc-sample-app.war
      source_link: https://github.com/asgardeo/asgardeo-tomcat-oidc-agent
    - name: Asgardeo Tomcat SAML Agent
      icon: assets/img/logo/java-logo.svg
      description: An Asgardeo SAML Tomcat agent for implementing SAML login/logout for Tomcat web apps
      documentation_link: get-started/try-your-own-app/java-ee-saml/
      download_link: https://github.com/asgardeo/asgardeo-tomcat-saml-agent/releases/latest/download/sample-app.war
      source_link: https://github.com/asgardeo/asgardeo-tomcat-saml-agent
    - name: Flutter AppAuth
      icon: assets/img/logo/flutter-logo.svg
      description: A wrapper for native AppAuth SDKs to integrate OAuth2 and OIDC providers into Flutter apps
      source_link: https://github.com/MaikuB/flutter_appauth/tree/master/flutter_appauth
    - name: React Native AppAuth
      icon: assets/img/logo/react-logo.svg
      description: An SDK to integrate OAuth2 and OIDC providers into React Native apps
      source_link: https://github.com/FormidableLabs/react-native-app-auth
    - name: AppAuth Android
      icon: assets/img/logo/android-logo.svg
      description: A client SDK to integrate OAuth2 and OIDC providers into Android applications
      source_link: https://github.com/openid/AppAuth-Android
    - name: AppAuth iOS
      icon: assets/img/logo/apple-idp-illustration.svg
      description: A client SDK to integrate OAuth2 and OIDC providers into iOS applications
      source_link: https://github.com/openid/AppAuth-iOS
  versions:
    current: 6.1.0
    list: 
      - 6.1.0
      - 6.0.0
      - 5.11.0
    all:
      - name: 6.1.0
        doc: https://is.docs.wso2.com/en/6.1.0
        notes: https://is.docs.wso2.com/en/6.1.0/references/about-this-release
      - name: 6.0.0
        doc: https://is.docs.wso2.com/en/6.0.0
        notes: https://is.docs.wso2.com/en/6.0.0/references/about-this-release
      - name: 5.11.0
        doc: https://is.docs.wso2.com/en/5.11.0
        notes: https://is.docs.wso2.com/en/5.11.0/get-started/about-this-release
      - name: 5.10.0
        doc: https://is.docs.wso2.com/en/5.10.0
        notes: https://is.docs.wso2.com/en/5.10.0/get-started/about-this-release
      - name: 5.9.0
        doc: https://is.docs.wso2.com/en/5.9.0
        notes: https://is.docs.wso2.com/en/5.9.0/get-started/about-this-release
      - name: 5.8.0
        doc: https://wso2docs.atlassian.net/wiki/spaces/IS580/overview
        notes: https://wso2docs.atlassian.net/wiki/spaces/IS580/pages/41124119/About+this+release
      - name: 5.7.0
        doc: https://wso2docs.atlassian.net/wiki/spaces/IS570/overview
        notes: https://wso2docs.atlassian.net/wiki/spaces/IS570/pages/38174879/About+this+Release
      - name: 5.6.0
        doc: https://wso2docs.atlassian.net/wiki/spaces/IS560/overview
        notes: https://wso2docs.atlassian.net/wiki/spaces/IS560/pages/31817769/About+this+Release
      - name: 5.5.0
        doc: https://wso2docs.atlassian.net/wiki/spaces/IS550/overview
        notes: https://wso2docs.atlassian.net/wiki/spaces/IS550/pages/29720727/About+this+Release
      - name: 5.4.1
        doc: https://wso2docs.atlassian.net/wiki/spaces/IS541/overview
        notes: https://wso2docs.atlassian.net/wiki/spaces/IS541/pages/42827813/About+this+Release
      - name: 5.4.0
        doc: https://wso2docs.atlassian.net/wiki/spaces/IS540/overview
        notes: https://wso2docs.atlassian.net/wiki/spaces/IS540/pages/45645861/About+this+Release
      - name: 5.3.0
        doc: https://wso2docs.atlassian.net/wiki/spaces/IS530/overview
        notes: https://wso2docs.atlassian.net/wiki/spaces/IS530/pages/25559702/About+this+Release
      - name: 5.2.0
        doc: https://wso2docs.atlassian.net/wiki/spaces/IS520/overview
        notes: https://wso2docs.atlassian.net/wiki/spaces/IS520/pages/47022087/About+this+Release
      - name: 5.1.0
        doc: https://wso2docs.atlassian.net/wiki/spaces/IS510/overview
        notes: https://wso2docs.atlassian.net/wiki/spaces/IS510/pages/25722900/About+this+Release
      - name: 5.0.0
        doc: https://wso2docs.atlassian.net/wiki/spaces/IS500/overview
        notes: https://wso2docs.atlassian.net/wiki/spaces/IS500/pages/32342518/About+this+Release
  redoc_theme: '{
    "colors": {
      "primary": { "main": "#ff7300" }
    }
  }'
