name: Link Checker 7

on:
  schedule:
    - cron: '0 0 1 * *'
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
      tags:
        description: 'Test scenario tags'
      websiteUrl:
        description: 'Website URL to check'
        required: true
        default: 'https://is.docs.wso2.com/en/latest'

jobs:
  website-checker:
    name: Link Checker
    runs-on: ubuntu-latest
    continue-on-error: true
    env:
      WEBSITE_URL: ${{ github.event.inputs.websiteUrl }}
    steps:
      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - name: Setup Environment
        run: |
          pip3 install git+https://github.com/linkchecker/linkchecker.git
          mkdir ./logs

      - name: Check Links
        run: |
          linkchecker \
            --no-warnings  \
            -t 100 \
            -o html \
            --ignore-url /internal/* \
            --ignore-url /some_other_directory/~.* \
            --ignore-url /*\.extension \
            $WEBSITE_URL > ./logs/$WEBSITE_URL.html

      # ... (rest of the workflow remains the same)
