name: Check Links on Live Site 5

on:
  workflow_dispatch:
    inputs:
      site-url:
        description: 'Live Site URL'
        required: true

jobs:
  check-links:
    runs-on: ubuntu-latest
    steps:
    - name: Run LinkChecker
      run: docker run --rm linkchecker/linkchecker ${{ github.event.inputs.site-url }} --check-extern
